version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - curl -LO https://github.com/dotnet/docfx/releases/download/v2.78.3/docfx-linux-x64-v2.78.3.zip -o docfx.zip
      - unzip docfx.zip -d docfx
      - ./docfx/docfx build
      - mkdir -p build/html
      - cp -r _site/* build/html/

sphinx:
  configuration: none