version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - curl -LO https://github.com/dotnet/docfx/releases/latest/download/docfx.zip
      - unzip docfx.zip -d docfx
      - ./docfx/docfx ./docs/docfx.json build

sphinx:
  configuration: none

html:
  base: docs/_site