version: '3.8'

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=VeryGoodPassword!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - urlshortener-network  

  urlshortener-backend:
    build:
      context: .
      dockerfile: UrlShortener.App.Backend/Dockerfile
    ports:
      - "6060:6060"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:6060
      - ConnectionStrings__MsSql=Server=mssql-db;Database=urlshortener;User=sa;Password=VeryGoodPassword!;TrustServerCertificate=true
    networks:
      - urlshortener-network
    depends_on:
      - mssql-db

  urlshortener-frontend:
    build:
      context: .
      dockerfile: UrlShortener.App.Blazor/UrlShortener.App.Blazor/Dockerfile
    ports:
      - "1010:8080"
      - "1011:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Backend__BaseUrl=http://urlshortener-backend:6060
    networks:
      - urlshortener-network
    depends_on:
      - urlshortener-backend
  
networks:
  urlshortener-network:
    driver: bridge

volumes:
  mssql-data:
    driver: local