@startuml Komponentendiagramm Backend

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

LAYOUT_LEFT_RIGHT()

Container(frontend, "Web-Anwendung", "Blazor Server", "Stellt die Benutzeroberfläche bereit, über die Nutzer URLs kürzen, verwalten und Tracking-Daten einsehen können.")
ContainerDb(db, "Relationale Datenbank", "Microsoft SQL Server", "Speichert Benutzerkonten, Kurz-URLs und Klick-Tracking-Daten.")
System_Ext(apicagent_api, "ApicAgent API", "Externer Dienst zur Analyse und Interpretation von User-Agent-Strings.")

Container_Boundary(backend, "Backend") {
    
    Component(auth, "AuthController", "ASP.NET Core Controller", "Verwaltet Login, Registrierung und Tokenvergabe.")
    Component(mappings, "MappingsController", "ASP.NET Core Controller", "Ermöglicht das Erstellen, Abrufen und Löschen von Kurz-URLs.")
    Component(redirect, "RedirectController", "ASP.NET Core Controller", "Verarbeitet Aufrufe von Kurz-URLs und löst Tracking aus.")
    
    Component(dataaccess, "AppDbContext", "Entity Framework Core", "Zugriff auf Benutzer-, URL- und Trackingdaten in der Datenbank.")
    Component(mappingsservice, "MappingsService", "C# Service", "Zugriff auf CRUD-Operations für URL-Daten.")
    Component(redirectlogservice, "RedirectLogService", "C# Service", "Ermöglicht das Erstellen von Tracking-Logs.")
    Component(useragentservice, "UserAgentService", "C# Service", "Analysiert User-Agent-Strings.")

    Rel(auth, dataaccess, "Liest und schreibt Nutzer")
    Rel(mappings, mappingsservice, "Verwendet")
    Rel(mappingsservice, dataaccess, "Erstellt, aktualisiert und löscht Daten")
    Rel(redirect, redirectlogservice, "Verwendet zum Tracking")
    Rel(redirect, mappingsservice, "Verwendet zur Abfrage der Ziel-URL")
    Rel(redirect, useragentservice, "Verwendet zur Analyse des User-Agents")
    Rel(redirectlogservice, dataaccess, "Schreibt Tracking-Logs")
    Rel(useragentservice, apicagent_api, "Analysiert User-Agent", "HTTPS")
}

Rel(frontend, auth, "Verwendet", "JSON/HTTPS")
Rel(frontend, mappings, "Verwendet", "JSON/HTTPS")
Rel(frontend, redirect, "Nicht direkt verwendet") ' nur extern über Klicks
Rel(dataaccess, db, "Liest und schreibt", "SQL")

@enduml