name: Security Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    needs: 
        - test

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: "UrlShortener.App"
        path: "."
        format: "HTML"
        args: >
          --failOnCVSS 7
          --enableRetired

    - name: Upload Dependency Check Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: reports/dependency-check-report.html